src/AppBundle/Entity/Orders.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Orders
 *
 * @ORM\Table(name="orders")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\OrdersRepository")
 */
class Orders implements \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="order_number", type="string", length=255)
     */
    private $orderNumber;

    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=255)
     * @Assert\NotBlank(groups={"buy"})
     * @Assert\Image(maxSize = "2M", groups={"buy"})
     */
    private $photo;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="integer", options={"default":"1"})
     * @Assert\NotNull(groups={"set_status"})
     */
    private $status;

    /**
     * @ORM\Column(name="back_panel", type="string")
     */
    private $backPanel;

    /**
     * @ORM\Column(name="back_panel_price", type="decimal", precision=8, scale=0)
     */
    private $backPanelPrice;

    /**
     * @ORM\Column(name="is_paid", type="boolean", options={"default": false})
     */
    private $isPaid;

    /**
     * @ORM\Column(name="total_price", type="decimal", precision=8, scale=0)
     */
    private $totalPrice;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * @see \Serializable::serialize()
     * @return string
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->photo
        ));
    }

    /**
     * @see \Serializable::unserialize()
     * @param string $serialized
     */
    public function unserialize($serialized)
    {
        list (
            $this->id
            ) = unserialize($serialized);
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set userId
     *
     * @param User $user
     * @return Orders
     * @internal param int $user
     *
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get userId
     *
     * @return int
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set orderNumber
     *
     * @param string $orderNumber
     *
     * @return Orders
     */
    public function setOrderNumber($orderNumber)
    {
        $this->orderNumber = $orderNumber;

        return $this;
    }

    /**
     * Get orderNumber
     *
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->orderNumber;
    }

    /**
     * Set photo
     *
     * @param string $photo
     *
     * @return Orders
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set status
     *
     * @param string $status
     *
     * @return Orders
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get readable status
     *
     * @return string
     */
    public function getReadableStatus()
    {
        if ($this->status == 1) {
            return 'Accepted';
        } elseif ($this->status == 2) {
            return 'Shipped';
        } else {
            return 'Fulfilled';
        }
    }

    /**
     * @param $createdAt
     * @return mixed
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $createdAt;
    }

    /**
     * Get created at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return mixed
     */
    public function getBackPanel()
    {
        return $this->backPanel;
    }

    /**
     * @param mixed $backPanel
     */
    public function setBackPanel($backPanel)
    {
        $this->backPanel = $backPanel;
    }

    /**
     * @return mixed
     */
    public function getBackPanelPrice()
    {
        return $this->backPanelPrice;
    }

    /**
     * @param mixed $backPanel
     * @return float
     */
    public function setBackPanelPrice($backPanel)
    {
        if ($backPanel == 'metal') {
            $this->backPanelPrice = '50.00';
        } elseif ($backPanel == 'glass') {
            $this->backPanelPrice = '100.00';
        } else {
            $this->backPanelPrice = 0;
        }

        return $this->backPanelPrice;
    }

    /**
     * @return mixed
     */
    public function getIsPaid()
    {
        return $this->isPaid;
    }

    /**
     * @param mixed $isPaid
     */
    public function setIsPaid($isPaid)
    {
        $this->isPaid = $isPaid;
    }

    /**
     * @return string
     */
    public function getReadableIsPaid()
    {
        if ($this->isPaid) {
            return 'Paid';
        }

        return 'Waiting for payment';
    }

    /**
     * @return mixed
     */
    public function getTotalPrice()
    {
        return $this->totalPrice;
    }

    /**
     * @param mixed $totalPrice
     */
    public function setTotalPrice($totalPrice)
    {
        $this->totalPrice = $totalPrice;
    }
}

src/AppBundle/Controller/DashboardController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class DashboardController extends Controller
{

    /**
     * @Route("/", name="admin_index")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $latestUsers = $em->getRepository('AppBundle:User')
            ->getLatestTenUsers();

        $usersCount = $em->getRepository('AppBundle:User')
            ->getUsersCount();

        $latestOrders = $em->getRepository('AppBundle:Orders')
            ->getLatestTenOrders();

        $fulfilledOrdersCount = $em->getRepository('AppBundle:Orders')
            ->getFulfilledOrdersCount();

        return $this->render('AppBundle:Dashboard:index.html.twig', [
            'latestUsers'          => $latestUsers,
            'usersCount'           => $usersCount,
            'latestOrders'         => $latestOrders,
            'fulfilledOrdersCount' => $fulfilledOrdersCount
        ]);
    }
}

src/AppBundle/Resources/views/Dashboard/_navbar_user.html.twig
<li class="dropdown user user-menu">
    <!-- Menu Toggle Button -->
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <!-- The user image in the navbar-->
        <img src="{{ app.user.facebookPhoto }}" class="user-image" alt="User Image">
        <!-- hidden-xs hides the username on small devices so only the image appears. -->
        <span class="hidden-xs">{{ app.user.name }}</span>
    </a>
    <ul class="dropdown-menu">
        <!-- The user image in the menu -->
        <li class="user-header">
            <img src="{{ app.user.facebookPhoto }}" class="img-circle" alt="User Image">

            <p>
                {{ app.user.name }}
            </p>
        </li>
        <!-- Menu Footer-->
        <li class="user-footer">
            {#<div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
            </div>#}
            <div class="pull-right">
                <a href="{{ path('security_logout') }}" class="btn btn-default btn-flat">Sign out</a>
            </div>
        </li>
    </ul>
</li>

src/AppBundle/Resources/views/Dashboard/_orders_list.html.twig
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Order No</th>
        <th>Created at</th>
        <th>Status</th>
        <th>Payment state</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.orderNumber }}</td>
            <td>{{ order.createdAt|date('Y-m-d') }}</td>
            <td>{{ order.readableStatus }}</td>
            <td>{{ order.readableIsPaid }}</td>
            <td><a href="{{ path('admin_orders_view', {'id': order.id}) }}" class="btn btn-default">View</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="navigation">
    {{ knp_pagination_render(orders) }}
</div>

src/AppBundle/Resources/views/Dashboard/base.html.twig
{% extends 'AvanzuAdminThemeBundle:layout:default-layout.html.twig' %}

{% block avanzu_logo_path %}{{ path('admin_index') }}{% endblock %}

{% block avanzu_document_title %}Zomge{% endblock %}

{% block avanzu_page_subtitle %}{% endblock %}

{% block avanzu_navbar_user %}
    {{ include('@App/Dashboard/_navbar_user.html.twig') }}
{% endblock %}

{% block avanzu_page_content %}
    {{ include('@App/_flash.html.twig') }}
{% endblock %}

{% block avanzu_sidebar_search %}{% endblock %}
{% block avanzu_navbar_control_sidebar_toggle %}{% endblock %}

src/AppBundle/Resources/views/Dashboard/index.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_page_title %}Dashboard{% endblock %}

{% block avanzu_page_content %}
    <div class="row">
        {# Orders Count #}
        <div class="col-md-6">
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>{{ fulfilledOrdersCount[0][1] }}</h3>
                    <p>Fulfilled Orders</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
            </div>
        </div>

        {# Users Count #}
        <div class="col-md-6">
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>{{ usersCount[0][1] }}</h3>
                    <p>Registered Users</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {# Latest users #}
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Latest users</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Registered</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in latestUsers %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.name }}</td>
                                <td>{{ user.email }}</td>
                                <td><a href="{{ path('admin_users_edit', {'id': user.id}) }}" class="btn btn-sm btn-default">Edit</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="box-footer clearfix">
                    <a href="{{ path('admin_users_index') }}" class="btn btn-sm btn-default btn-flat pull-right">View All Users</a>
                </div>
            </div>
        </div>

        {# Latest orders #}
        <div class="col-md-6">
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="title with-border">
                        <h3 class="box-title">Latest orders</h3>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Order No</th>
                            <th>Created at</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in latestOrders %}
                            <tr>
                                <td>{{ order.orderNumber }}</td>
                                <td>{{ order.createdAt|date('Y-m-d') }}</td>
                                <td>{{ order.readableStatus }}</td>
                                <td><a href="{{ path('admin_orders_view', {'id': order.id}) }}" class="btn btn-sm btn-default">View</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="box-footer clearfix">
                    <a href="{{ path('admin_orders_index') }}" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

src/AppBundle/Resources/views/Dashboard/orders_index.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_page_title %}Orders{% endblock %}

{% block avanzu_page_content %}
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Order No</th>
                            <th>Created at</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.id }}</td>
                                <td>{{ order.orderNumber }}</td>
                                <td>{{ order.createdAt|date('Y-m-d') }}</td>
                                <td><a href="{{ path('admin_orders_view', {'id': order.id}) }}" class="btn btn-default">View</a></td>
                                {#<td><a href="{{ path('admin_users_edit', {'id': user.id}) }}" class="btn btn-default">Edit</a></td>#}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Dashboard/orders_view.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_head %}
    <style>
        #phone {
            width: 250px;
            height: 500px;
            border-radius: 15px;
            position: relative;
            overflow: hidden
        }

        #phone img {
            position: absolute;
            left: 50%;
            top: 50%;
            height: 100%;
            width: auto;
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%)
        }

        #phone #camera {
            width: 100px;
            height: 50px;
            top: 15%
        }
    </style>
{% endblock %}

{% block avanzu_page_title %}Orders{% endblock %}
{% block avanzu_page_subtitle %}View order #{{ order.orderNumber }}{% endblock %}

{% block avanzu_page_content %}
    {{ parent() }}

    <div class="row">
        <div class="col-md-3 col-sm-12">
            <div class="box">
                <div class="box-body">
                    <div id="phone">
                        <img src="/uploads/{{ order.photo }}">
                        <img src="{{ asset('images/camera.png') }}" alt="Camera" id="camera">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-9 col-sm-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Customer detail</h3>
                </div>
                <div class="box-body">
                    <p><strong>Name:</strong> {{ order.user.name }}</p>
                    <p><strong>Address:</strong> {{ order.user.address }}</p>
                    <p><strong>City:</strong> {{ order.user.city }}</p>
                    <p><strong>Postal code:</strong> {{ order.user.postalCode }}</p>
                    <p><strong>Phone no.:</strong> {{ order.user.phoneNumber }}</p>
                </div>
            </div>

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Status</h3>
                </div>
                <div class="box-body">
                    {{ form(form) }}

                    <strong>Payment status:</strong> {{ order.readableIsPaid }}
                </div>
            </div>

            <div class="box box-warning">
                <table class="table">
                    <thead>
                        <th>Item</th>
                        <th class="col-md-1">Price</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Zomge Q1</td>
                            <td>399&euro;</td>
                        </tr>
                        <tr>
                            <td>Back panel material: {{ order.backPanel }}</td>
                            <td>{{ order.backPanelPrice }}&euro;</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div class="text-right" style="margin-right: 1em;">
                                    <h4>Total price: {{ order.totalPrice }}&euro;</h4>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Dashboard/users.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_page_title %}Users{% endblock %}

{% block avanzu_page_content %}
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.name }}</td>
                                <td>{{ user.email }}</td>
                                <td><a href="#" class="btn btn-default">Edit</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Dashboard/users_edit.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_page_title %}Users{% endblock %}

{% block avanzu_page_content %}
    {{ parent() }}

    <div class="box">
        <div class="box-body">
            {{ form(form) }}
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Dashboard/users_index.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_page_title %}Users{% endblock %}

{% block avanzu_page_content %}
    {{ parent() }}

    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Registered</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.name }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.createdAt|date('Y-m-d') }}</td>
                                <td>
                                    <a href="{{ path('admin_users_edit', {'id': user.id}) }}" class="btn btn-default">Edit</a>
                                    <a href="{{ path('admin_users_orders', {'id': user.id}) }}" class="btn btn-primary">Orders</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    <div class="navigation">
                        {{ knp_pagination_render(users) }}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Dashboard/users_orders.html.twig
{% extends "@App/Dashboard/base.html.twig" %}

{% block avanzu_page_title %}Orders{% endblock %}
{% block avanzu_page_subtitle %}View {{ user.name }} orders{% endblock %}

{% block avanzu_page_content %}

    <div class="box">
        <div class="box-body">
            {% if orders is empty %}
                <div class="alert alert-info" role="alert">
                    This user hasn't made any orders yet.
                </div>
            {% else %}
                {% include 'AppBundle:Dashboard:_orders_list.html.twig' %}
            {% endif %}
        </div>
    </div>

{% endblock %}